workflows:
  ios-workflow:
    name: Build iOS IPA with XcodeGen
    environment:
      xcode: latest
      cocoapods: default
      swift: latest
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen || echo "XcodeGen already installed"
      - name: Generate Xcode project
        script: |
          xcodegen generate
      - name: Install dependencies
        script: |
          pod install || echo "No pods to install"
      - name: Build IPA
        script: |
          xcodebuild -workspace DiaryApp.xcworkspace -scheme DiaryApp -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/DiaryApp.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/DiaryApp.xcarchive -exportPath $CM_BUILD_DIR/ -exportOptionsPlist ExportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/*.ipa
    publishing:
      email:
        recipients:
          - bilalsaghir.uk@gmail.com
        on_success: always
        on_failure: always
    triggers:
      - event: push
        branch:
          - main
